version: "3"
services:
  portainer:
    build:
      context: "./portainer"
    volumes:
      - "${DATA_PATH_HOST}/portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${PORTAINER_PORT}:9000"
volumes: {}
